### ISSUE TITLE
url demo

### ISSUE THREAD

**Issue by johnfelipe** [ScottKbka/open_parliament#1]
url demo
pls

**Comment by ScottKbka** [comment]
Hi @johnfelipe this was a personal project to see what I could find in the data from this website: https://openparliament.ca/

I see you do similar stuff in Colombia. You should look at https://github.com/CivicHaxx/ok_councillr It's an app for learning more about city politics. I'm hoping to have a demo site up this week.

**Comment by johnfelipe** [comment]
Do you have demo site up?

**Comment by ScottKbka** [comment]
http://okcouncillr.cloudapp.net/

**Comment by johnfelipe** [comment]
But about open_parliament

**Comment by ScottKbka** [comment]
See my original comment. https://openparliament.ca/ is where I got this data from.

**Comment by johnfelipe** [comment]
Do you have cheatsheet for okcouncilir?
